### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by ludberg** [aalteirac/spotifySessionApp#1]
Hi

I watched your talk here at Qonnections and I wanted to try this since it was a very nice solution. 
I'm having some trouble getting this to work. 

What I get is: "GET http://10.76.224.67/ano/resources/js/qlik.js net::ERR_CONNECTION_TIMED_OUT"

What I did was:
1) Edit the config.js and added my spotify key (no other changes!)
2) Created a new virtual proxy with 

- session name X-sess, 
- added the Session Module URI, 
- set the prefix to ano
- session cookie domain set to localhost
- Additional respose headers: Access-Control-Allow-Origin:*
- Linked it to the proxy service

Run npm install and npm start. 

When I go to localhost:3002 I get redirected to Spotify and then back with a token. Now I get the abovementioned error. 

**What did I do wrong?** 

I can't recognize the ip address 10.76.224.67 as the machine I'm on has 10.101.***.***

**Comment by aalteirac** [comment]
Hi ludberg, 

thanks for your interest, I need to update the readme, indeed there's an harcoded IP in the code: public/spotify-session-app.js, line 18:
`var config = {
		host: '10.76.224.67',
		prefix: '/ano/',
		port: 80,
		isSecure: false
	};`

just change it to point you sense server.

Hope it helps,

**Comment by ludberg** [comment]
Hi

I changed to 'localhost' and now I get this error.

Can you point me in the right direction?

Best
Anders

[image: Inline image 2]

Anders Uddenberg
*070 29 41 012*

**Comment by aalteirac** [comment]
Cannot see the picture unfortunately, could you post it again or paste the stack as text ?

Many thanks

**Comment by ludberg** [comment]
Upon further investigation I get the following error.

Might it be something with my Virtual Proxy?
Do I need to change the Default App ID, or Directory?

Hostname is set to localhost and I can use the Qlik Sense Enterprise server
that's on http://localhost

*ERROR on createSessionApp Error: Not connected*
    at RPC.send
(C:\Users\anders.uddenberg\Downloads\spotifySessionApp\node_modu
les\enigma.js\dist\enigma.js:2759:37)
    at Session.send
(C:\Users\anders.uddenberg\Downloads\spotifySessionApp\node_
modules\enigma.js\dist\enigma.js:1501:32)
    at Object.fn [as getActiveDoc]
(C:\Users\anders.uddenberg\Downloads\spotifyS
essionApp\node_modules\enigma.js\dist\enigma.js:2467:32)
    at qix.global.createSessionApp.then
(C:\Users\anders.uddenberg\Downloads\spo
tifySessionApp\engine.js:166:25)
    at process._tickCallback (internal/process/next_tick.js:109:7)
*Error: Not connected*
    at RPC.send
(C:\Users\anders.uddenberg\Downloads\spotifySessionApp\node_modu
les\enigma.js\dist\enigma.js:2759:37)
    at Session.send
(C:\Users\anders.uddenberg\Downloads\spotifySessionApp\node_
modules\enigma.js\dist\enigma.js:1501:32)
    at Object.fn [as getActiveDoc]
(C:\Users\anders.uddenberg\Downloads\spotifyS
essionApp\node_modules\enigma.js\dist\enigma.js:2467:32)
    at qix.global.createSessionApp.then
(C:\Users\anders.uddenberg\Downloads\spo
tifySessionApp\engine.js:166:25)
    at process._tickCallback (internal/process/next_tick.js:109:7)



Anders Uddenberg
*070 29 41 012*

**Comment by aalteirac** [comment]
oki, sounds like the backend is not able to connect, is your proxy set to accept http ?

**Comment by aalteirac** [comment]
You can now test also on Qlik Sense Desktop, far easier to setup.

Let me know !

Thanks

**Comment by ludberg** [comment]
It almost worked with desktop, the object "qlik" is undefined in
spotify-session-app.js. See error below

spotify-session-app.js:55 Uncaught TypeError: Cannot read property
'sessionAppFromApp' of undefined
    at Object.success (spotify-session-app.js:55)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.b (jquery.min.js:4)
(anonymous) @ spotify-session-app.js:55


Anders Uddenberg
*070 29 41 012*

On Tue, May 23, 2017 at 10:06 AM, Anthony Alteirac <notifications@github.com

**Comment by aalteirac** [comment]
Thanks for feedback Anders ! Let's start from the beginning, what's your desktop version (must be SR3 min) ? Did you checkout the latest code ?

**Comment by ludberg** [comment]
Hi

I upgraded to latest (SR4) and it worked perfectly.

Thanks for you patience!

Best

Anders Uddenberg
*070 29 41 012*

On Wed, May 24, 2017 at 10:38 AM, Anthony Alteirac <notifications@github.com

**Comment by aalteirac** [comment]
Thanks Anders !
